
server:
  port: 8080


spring:
  application:
    name: cloud-native-gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://localhost:9090
          predicates:
            - Path=/test/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1   #
                redis-rate-limiter.burstCapacity: 3   #
                key-resolver: "#{@pathKeyResolver}"   #

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8 # ????
          max-idle: 8 # ??????
          min-idle: 0 # ??????
          max-wait: 100 # ??????